### ISSUE TITLE
No module named yaml

### ISSUE THREAD

**Issue by CMUnreal** [ihinsdale/mean-local-auth#4]
What should i do with the error "ERROR! Unexpected Exception: No module named yaml" This comes up after the command, ansible-playbook -i development site.yml -vvvv

I read https://www.virtxpert.com/installing-ansible-2-1-devel-from-source-on-ubuntu-15-10/ Thus, does MLA require Debian 8 with Python 2.7.9 or Ubuntu 15.10? Thx

Anyway thanks for providing this git, learned a lot.

**Comment by ihinsdale** [comment]
Glad it was helpful to you!

Seems like a yaml dependency issue--do you have PyYAML installed? Also, something to keep in mind is that at the time I was working on this, I was using something like v1.7 of Ansible. If you're using v2.1, you may run into problems.
